version: '3'

services:
  app:
    build: 
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - ./:/home/node/app
      - /home/node/app/node_modules
